//! TTD FFI types — single import point for downstream modules.
//!
//! `bindings` — auto-generated TTD SDK enum types + constants (from `ttd_bindings.h`)
//! `ffi` — wrapper projection types + functions (from `ttd_wrapper.h`)
//!
//! Downstream code imports `crate::ttd::types::*` and gets everything needed
//! without touching the raw bindgen modules directly.

// ─── SDK enum types (auto-generated from TTD SDK via bindgen -x c++) ─
pub use crate::ttd::bindings::{
    TTD_Replay_DataAccessMask, TTD_Replay_EventMask, TTD_Replay_EventType, TTD_Replay_ExceptionMask,
};

// ─── SDK enum constants (auto-generated, values match TTD::Replay::EventType etc.) ─
pub use crate::ttd::bindings::{
    TTD_Replay_DataAccessMask_All, TTD_Replay_DataAccessMask_Execute,
    TTD_Replay_DataAccessMask_None, TTD_Replay_DataAccessMask_Read,
    TTD_Replay_DataAccessMask_Write, TTD_Replay_EventMask_All, TTD_Replay_EventMask_Exception,
    TTD_Replay_EventMask_Gap, TTD_Replay_EventMask_MemoryWatchpoint,
    TTD_Replay_EventMask_PositionWatchpoint, TTD_Replay_EventMask_Thread,
    TTD_Replay_EventType_Error, TTD_Replay_EventType_Exception, TTD_Replay_EventType_Gap,
    TTD_Replay_EventType_Interrupted, TTD_Replay_EventType_MemoryWatchpoint,
    TTD_Replay_EventType_Position, TTD_Replay_EventType_PositionWatchpoint,
    TTD_Replay_EventType_Process, TTD_Replay_EventType_StepCount, TTD_Replay_EventType_Thread,
    TTD_Replay_ExceptionMask_All, TTD_Replay_ExceptionMask_CPlusPlus,
    TTD_Replay_ExceptionMask_DebugPrint, TTD_Replay_ExceptionMask_Hardware,
    TTD_Replay_ExceptionMask_Software,
};

// ─── Wrapper projection types (from ttd_wrapper.h, auto-generated) ──
pub use crate::ttd::ffi::{
    TtdActiveThreadInfo, TtdExceptionEvent, TtdPosition, TtdPositionRange, TtdReplayResult,
    TtdThreadInfo, TtdX64Regs,
};

// ─── Extra trait impls not generated by bindgen ─────────────────────

impl PartialOrd for TtdPosition {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for TtdPosition {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        match self.sequence.cmp(&other.sequence) {
            std::cmp::Ordering::Equal => self.steps.cmp(&other.steps),
            ord => ord,
        }
    }
}
