//! TTD FFI types — single import point for downstream modules.
//!
//! `bindings` — auto-generated TTD SDK enum types + constants (from `ttd_bindings.h`)
//! `ffi` — wrapper projection types + functions (from `ttd_wrapper.h`)
//!
//! Downstream code imports `crate::ttd::types::*` and gets everything needed
//! without touching the raw bindgen modules directly.

// ─── SDK enum types (auto-generated from TTD SDK via bindgen -x c++) ─
pub use crate::ttd::bindings::{
    TTD_Replay_DataAccessMask, TTD_Replay_EventMask, TTD_Replay_EventType, TTD_Replay_ExceptionMask,
};

// ─── SDK enum constants (auto-generated, values match TTD::Replay::EventType etc.) ─
pub use crate::ttd::bindings::{
    TTD_Replay_DataAccessMask_All, TTD_Replay_DataAccessMask_Execute,
    TTD_Replay_DataAccessMask_None, TTD_Replay_DataAccessMask_Read,
    TTD_Replay_DataAccessMask_Write, TTD_Replay_EventMask_All, TTD_Replay_EventMask_Exception,
    TTD_Replay_EventMask_Gap, TTD_Replay_EventMask_MemoryWatchpoint,
    TTD_Replay_EventMask_PositionWatchpoint, TTD_Replay_EventMask_Thread,
    TTD_Replay_EventType_Error, TTD_Replay_EventType_Exception, TTD_Replay_EventType_Gap,
    TTD_Replay_EventType_Interrupted, TTD_Replay_EventType_MemoryWatchpoint,
    TTD_Replay_EventType_Position, TTD_Replay_EventType_PositionWatchpoint,
    TTD_Replay_EventType_Process, TTD_Replay_EventType_StepCount, TTD_Replay_EventType_Thread,
    TTD_Replay_ExceptionMask_All, TTD_Replay_ExceptionMask_CPlusPlus,
    TTD_Replay_ExceptionMask_DebugPrint, TTD_Replay_ExceptionMask_Hardware,
    TTD_Replay_ExceptionMask_Software,
};

// ─── Wrapper projection types (from ttd_wrapper.h, auto-generated) ──
pub use crate::ttd::ffi::{
    TtdActiveThreadInfo, TtdExceptionEvent, TtdPosition, TtdPositionRange, TtdReplayResult,
    TtdThreadInfo, TtdX64Regs,
};

// ─── Extra trait impls not generated by bindgen ─────────────────────

impl PartialOrd for TtdPosition {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for TtdPosition {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        match self.sequence.cmp(&other.sequence) {
            std::cmp::Ordering::Equal => self.steps.cmp(&other.steps),
            ord => ord,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn pos(sequence: u64, steps: u64) -> TtdPosition {
        TtdPosition { sequence, steps }
    }

    /// Trace positions are `(sequence, steps)` pairs ordered
    /// lexicographically: `sequence` is the coarse axis (a thread quantum),
    /// `steps` only breaks ties inside one sequence. Every trace-boundary and
    /// clamping decision in the target layer (`goto`, `TraceStart`/`TraceEnd`
    /// detection) relies on this ordering.
    #[test]
    fn positions_order_by_sequence_then_steps() {
        assert!(pos(1, 0) < pos(2, 0));
        assert!(pos(1, 5) < pos(1, 6));
        // A bigger sequence always wins, whatever the steps say.
        assert!(pos(1, u64::MAX) < pos(2, 0));
        assert!(pos(5, 100) > pos(5, 99));
        assert_eq!(pos(0x755, 0x67), pos(0x755, 0x67));
    }

    #[test]
    fn ordering_is_total_and_consistent() {
        use std::cmp::Ordering;
        let sorted = [
            pos(0, 0),
            pos(0, 1),
            pos(1, 0),
            pos(1, 1),
            pos(2, 0),
            pos(0x755, 0x67),
            pos(0x755, 0x68),
        ];
        for w in sorted.windows(2) {
            assert_eq!(w[0].cmp(&w[1]), Ordering::Less, "{:?} vs {:?}", w[0], w[1]);
            assert!(w[0] < w[1]);
            assert!(w[1] > w[0]);
            assert_ne!(w[0], w[1]);
        }
        // PartialOrd must agree with Ord (it is derived from it).
        assert_eq!(pos(1, 2).partial_cmp(&pos(1, 3)), Some(Ordering::Less));
        assert_eq!(pos(2, 0).partial_cmp(&pos(1, 9)), Some(Ordering::Greater));
        assert_eq!(pos(1, 1).partial_cmp(&pos(1, 1)), Some(Ordering::Equal));
        // min/max/clamp all come from this impl.
        assert_eq!(pos(3, 3).min(pos(3, 4)), pos(3, 3));
        assert_eq!(pos(3, 3).max(pos(3, 4)), pos(3, 4));
    }
}
